export CLOCK_SHOW_IT_IS="true"
export CLOCK_SHOW_A="true"
export CLOCK_INTERVAL="0.5"
export CLOCK_LIGHT_COLOR="#14944c"
export CLOCK_FACE_MODE="16x16"
export CLOCK_MODE="Normal"
export CLOCK_BAUD_RATE="1000"
